const { Schema, model } = require("../db/connection");

const TagSchema = new Schema({
  tags: {
    type: Array,
    default: [
      "Fantasy",
      "Books",
      "Movies",
      "TV",
      "Games",
      "Comics",
      "Music",
      "Art",
      "History",
      "Science",
      "Nature",
      "Travel",
      "Food",
      "Sports",
      "Cars",
      "Tech",
      "Fashion",
      "Home",
      "DIY",
      "Animals",
      "Health",
      "Fitness",
      "Beauty",
      "Parenting",
      "Relationships",
      "Career",
      "Money",
      "News",
      "Politics",
      "Religion",
      "Spirituality",
      "Humor",
      "Entertainment",
      "Education",
      "Science",
      "Nature",
      "Travel",
      "Food",
      "Sports",
      "Cars",
      "Tech",
      "Fashion",
      "Home",
      "DIY",
      "Animals",
      "Health",
      "Fitness",
      "Beauty",
      "Parenting",
      "Relationships",
      "Career",
      "Money",
      "News",
      "Politics",
      "Religion",
      "Spirituality",
      "Humor",
      "Entertainment",
      "Education",
    ],
  },
});

const Tag = model("Tag", TagSchema);

module.exports = Tag;
